### ISSUE TITLE
We should improve the look of the video archive

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#46]
https://semperplugins.com/doc-type/video/

**Comment by wpsmort** [comment]
Here's an example of how this could look with thumbnail images and titles for each video in a grid down the page:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/15794042/d44a437c-29b5-11e6-9f35-689e57d8a7f4.png)

**Comment by michaeltorbert** [comment]
I like it, except there should be some indication on the image that it links to a video, like they have at ithemes.com/tutorials/

**Comment by arnaudbroes** [comment]
@michaeltorbert @wpsmort 
Nadir Boukhe seems to be unavailable and does not answer my messages. Is there any other freelancer you recommend? Otherwise I'll look for someone myself.

**Comment by arnaudbroes** [comment]
@wpsmort 
Adrian just sent me the adjusted files for the theme. Took me a while to get in touch, he got a job now.
This is for the video section, to restyle the featured posts section for the blog on the homepage (and also fixing that alignment bug for one of the products on mobile I believe).

He said he also changed something so that visitors can actually view the grid with videos and the login prompt only activates when they click one. 

https://drive.google.com/file/d/0B4U9l2FcsW8BSF9rMVppNUJ1aGM/view?usp=sharing

The files that have been adjusted:

- functions.php
- style.css
- taxonomy-doc-type.php
- home.php

Let me know if he did an OK job, he's not a bad coder but not that familiar with WordPress.
Re-assign me if this needs more changes.

Related to issues #16 and #25.

**Comment by wpsmort** [comment]
This is done and tested.  Styling was added under this commit - https://github.com/semperfiwebdesign/semperpluginstheme/commit/ca6edc500456987345ab432603a2fd69c51aa706
